name: Multi Jobs Workflow

on: 
    workflow_dispatch:

jobs:
    multi-workflow-job:
        runs-on: ubumntu-latest

        steps: 
            - name: First Workflow Job
              run: | 
                echo "Hello, First Workflow!"

    second-workflow-job:
         runs-on: ubumntu-latest

         steps:
            - name: Second Workflow Job
              run: | 
                echo "Hello, Second Workflow!"



    