name: Dependent Multi Jobs Workflow

on: 
    workflow_dispatch:

jobs:
    first-workflow-job:
        runs-on: ubumntu-latest

        steps: 
            - name: First Workflow Job
              run: | 
                echo "Hello, First Workflow!"

    second-workflow-job:
         runs-on: ubumntu-latest
         needs: [first-workflow-job]

         steps:
            - name: Second Workflow Job
              run: | 
                echo "Hello, Second Workflow!"
    
    third-workflow-job:
         runs-on: ubumntu-latest
         needs: [first-workflow-job, second-workflow-job]

         steps:
            - name: Third Workflow Job
              run: | 
                echo "Hello, Third Workflow!"



    